content_hash: 02a29903fcd36d300c30565a842a66471d6e70d9ad5c6c818ff0ddd5a71093ae
files:
- coops_update.yml
idempotent: ansible
image: imgfile-coops-model
name: coops-update-playbook
operation: ansible
run: 2026_09_22t11_34_06_839905
type: ansible-default
